### ISSUE TITLE
Testing code errors: TypeError

### ISSUE THREAD

**Issue by lrunze** [qutip/qutip#1039]
Hi, 

I installed qutip on my windows system and tried the testing codes and faced the problem (as the figure shows):

TypeError: Cannot convert _UnitedFuncCaller to qutip.cy.cqobjevo_factor.CoeffFunc

![image](https://user-images.githubusercontent.com/13745165/60830800-9a9e5e00-a1ea-11e9-99d7-2ec24390083e.png)

Here is the about() information:

QuTiP: Quantum Toolbox in Python
Copyright (c) 2011 and later.
A. J. Pitchford, P. D. Nation, R. J. Johansson, A. Grimsmo, and C. Granade

QuTiP Version:      4.4.0.dev0
Numpy Version:      1.16.4
Scipy Version:      1.2.1
Cython Version:     0.29.11
Matplotlib Version: 3.1.0
Python Version:     3.7.3
Number of CPUs:     8
BLAS Info:          INTEL MKL
OPENMP Installed:   True
INTEL MKL Ext:      True
Platform Info:      Windows (AMD64)
Installation path:  C:\Anaconda\envs\qutip\lib\site-packages\qutip-4.4.0.dev0-py3.7-win-amd64.egg\qutip

I would appreciate it if you can give me some advice to help me pass the testing codes!

**Comment by Ericgig** [comment]
Hi,
This a manual installation of the master branch?
Are you using the qutip tests in qutip.testing.run(), if so could you tell us which test is failing? (And which similar only are not.)

**Comment by lrunze** [comment]
Hi Ericgig,

Thanks for your response!

I installed the qutip manually with master branch. And yes, I used the qutip.testing.run() to test if the installation and functions are ready.

I re-runned the testing and the error happened on the "**Monte-carlo: Collapse terms constant (func format)**".

Attached file is the error output with context.

[issue1039.txt](https://github.com/qutip/qutip/files/3373987/issue1039.txt)

Thanks!

**Comment by Ericgig** [comment]
Hi Irunze,
PR #1040 should fix that bug. 
Thank you for reporting.
Eric

**Comment by zhedie** [comment]
Has this problem been solved?

> Hi,
> 
> I installed qutip on my windows system and tried the testing codes and faced the problem (as the figure shows):
> 
> TypeError: Cannot convert _UnitedFuncCaller to qutip.cy.cqobjevo_factor.CoeffFunc
> 
> ![image](https://user-images.githubusercontent.com/13745165/60830800-9a9e5e00-a1ea-11e9-99d7-2ec24390083e.png)
> 
> Here is the about() information:
> 
> QuTiP: Quantum Toolbox in Python
> Copyright (c) 2011 and later.
> A. J. Pitchford, P. D. Nation, R. J. Johansson, A. Grimsmo, and C. Granade
> 
> QuTiP Version: 4.4.0.dev0
> Numpy Version: 1.16.4
> Scipy Version: 1.2.1
> Cython Version: 0.29.11
> Matplotlib Version: 3.1.0
> Python Version: 3.7.3
> Number of CPUs: 8
> BLAS Info: INTEL MKL
> OPENMP Installed: True
> INTEL MKL Ext: True
> Platform Info: Windows (AMD64)
> Installation path: C:\Anaconda\envs\qutip\lib\site-packages\qutip-4.4.0.dev0-py3.7-win-amd64.egg\qutip
> 
> I would appreciate it if you can give me some advice to help me pass the testing codes!

Hi, 
Has this problem been solved? I met this same problem installing qutip-4.4.0.

**Comment by zhedie** [comment]
> Hi,
> 
> I installed qutip on my windows system and tried the testing codes and faced the problem (as the figure shows):
> 
> TypeError: Cannot convert _UnitedFuncCaller to qutip.cy.cqobjevo_factor.CoeffFunc
> 
> ![image](https://user-images.githubusercontent.com/13745165/60830800-9a9e5e00-a1ea-11e9-99d7-2ec24390083e.png)
> 
> Here is the about() information:
> 
> QuTiP: Quantum Toolbox in Python
> Copyright (c) 2011 and later.
> A. J. Pitchford, P. D. Nation, R. J. Johansson, A. Grimsmo, and C. Granade
> 
> QuTiP Version: 4.4.0.dev0
> Numpy Version: 1.16.4
> Scipy Version: 1.2.1
> Cython Version: 0.29.11
> Matplotlib Version: 3.1.0
> Python Version: 3.7.3
> Number of CPUs: 8
> BLAS Info: INTEL MKL
> OPENMP Installed: True
> INTEL MKL Ext: True
> Platform Info: Windows (AMD64)
> Installation path: C:\Anaconda\envs\qutip\lib\site-packages\qutip-4.4.0.dev0-py3.7-win-amd64.egg\qutip
> 
> I would appreciate it if you can give me some advice to help me pass the testing codes!

Hi,
Has this problem been solved? I met this same error when installing qutip-4.4.0.

**Comment by Ericgig** [comment]
This bug is only in 4.4.0, the patch has not been released yet.
Don't use parallel_map in windows for mcsolve and stochastic solvers to go around it.
Or if you can install from source, the working version is in #1040

**Comment by zhedie** [comment]
> This bug is only in 4.4.0, the patch has not been released yet.
> Don't use parallel_map in windows for mcsolve and stochastic solvers to go around it.
> Or if you can install from source, the working version is in #1040

I download the version 4.4.1 from https://github.com/Ericgig/qutip/tree/4.4.1/qutip  but still met this 
problem.

**Comment by Ericgig** [comment]
See https://github.com/qutip/qutip/pull/1069
The code is (until merged) at https://github.com/qutip/qutip/tree/qutip-4.4.1.
Should be released next week.

**Comment by wpfff** [comment]
The version at the last link posted also gives me this error. Should that have been fixed in there?

**Comment by AliIssac** [comment]
Hi, I get many errors while running the test code, and at the end, I came up with a nitification that says (Failed(errors=12)). here are the errors:

td_brmesolve: passes all brmesolve tests ... ERROR
td_brmesolve: time-dependent a_ops ... ERROR
td_brmesolve: time-dependent a_ops tuple of strings ... ERROR
td_brmesolve: time-dependent a_ops tuple interp ... ERROR
td_brmesolve: time-dependent a_ops & c_ops interp ... ERROR
td_brmesolve: non-Hermitian e_ops check ... ERROR
td_brmesolve: states check ... ERROR
td_brmesolve: split ops #1 ... ERROR
td_brmesolve: split ops #2 ... ERROR
td_brmesolve: split ops, Cubic_Spline td-terms ... ERROR
td_brmesolve: split ops, multiple ... ERROR
td_brmesolve: Hamiltonian args ... ERROR


Please let me know how to fix it. thanks in advance

**Comment by saiyagami** [comment]
HI, I have some errors similar to these, and I don't know how to solve it. Is there anyone will face these problems if installing on windows?

**Comment by nathanshammah** [comment]
Hi @saiyagami, thanks. Are these still occurring with the 4.4.1 release?
