### ISSUE TITLE
Default steadystate method ("direct") fails with singular matrix in piqs.Dicke

### ISSUE THREAD

**Issue by ChaoXianGaoGuan** [qutip/qutip#2649]
Default steadystate method ("direct") fails with singular matrix in piqs.Dicke

When using the 'piqs.Dicke' class to compute the steady state, the default 'steadystate' method (method="direct") raises a "ValueError: Matrix is singular" error. Switching to method="eigen" works fine, and switching to method="svd" works well but very slow. 
This issue was encountered while following the piqs tutorial at https://qutip.readthedocs.io/en/latest/guide/guide-piqs.html. The same problem appears in the notebook at https://github.com/nathanshammah/notebooks/blob/master/qutip_tutorials/0.overview_ensembles_piqs.ipynb.

**Comment by ChehakTrehan** [comment]
@ChaoXianGaoGuan 
from qutip import piqs
N = 10
system = piqs.Dicke(N, emission = 1, pumping = 2)
L = system.liouvillian()
steady = steadystate(L)

This gives us error as here default method is direct which fails in singular matrix.
It can be corrected by using power or eigen method. Best method would be power as it is more stable , eigen is more accurate but it is slower 

So corrected line :-
steady = steadystate(L, method="power")

**Comment by ChaoXianGaoGuan** [comment]
@ChehakTrehan I used `method="power"` but still get error

`---------------------------------------------------------------------------
MatrixRankWarning                         Traceback (most recent call last)
File e:\anaconda3\envs\quantum\Lib\site-packages\qutip\core\data\solve.py:92, in solve_csr_dense(matrix, target, method, options)
     91 try:
---> 92     out = solver(M, b, **options)
     93 except splinalg.MatrixRankWarning:

File e:\anaconda3\envs\quantum\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:296, in spsolve(A, b, permc_spec, use_umfpack)
    295 if info != 0:
--> 296     warn("Matrix is exactly singular", MatrixRankWarning, stacklevel=2)
    297     x.fill(np.nan)

MatrixRankWarning: Matrix is exactly singular

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[5], line 5
      3 system = piqs.Dicke(N, emission = 1, pumping = 2)
      4 L = system.liouvillian()
----> 5 steady = steadystate(L,method="power")

File e:\anaconda3\envs\quantum\Lib\site-packages\qutip\solver\steadystate.py:186, in steadystate(A, c_ops, method, solver, **kwargs)
    184     A = A.to("csr")
    185     solver = "mkl_spsolve" if settings.has_mkl else "spsolve"
--> 186 elif solver is None and (kwargs.get("sparse", None) is False):
    187     # sparse is explicitly set to false, v4 tag to use `numpy.linalg.solve`
    188     A = A.to("dense")
    189     solver = "solve"

File e:\anaconda3\envs\quantum\Lib\site-packages\qutip\solver\steadystate.py:301, in _steadystate_power(A, **kw)
    298 # Propagator at an arbitrary long time
    299 prop = (propagator_T * L).expm()
--> 301 niter = 0
    302 max_iter = kw.get("propagator_max_iter", 30)
    303 while niter < max_iter:

File e:\anaconda3\envs\quantum\Lib\site-packages\qutip\core\data\dispatch.pyx:392, in qutip.core.data.dispatch.Dispatcher.__call__()

File e:\anaconda3\envs\quantum\Lib\site-packages\qutip\core\data\solve.py:94, in solve_csr_dense(matrix, target, method, options)
     92         out = solver(M, b, **options)
     93     except splinalg.MatrixRankWarning:
---> 94         raise ValueError("Matrix is singular")
     96 if isinstance(out, tuple) and len(out) == 2:
     97     # iterative method return a success flag
     98     out, check = out

ValueError: Matrix is singular`

**Comment by Ericgig** [comment]
The error `Matrix is singular` is expected when the steady state is degenerate.
For example:
```
H = qeye(2) & qeye(2)
c = [qeye(2) & destroy(2)]

steadystate(H, c, method=...)
```

There is no collapse for the first Qubit, so the solution is not unique. 
`steadystate` methods that are looking for a unique solution will fail, but those that look for some solutions will.
The methods `eigen`, `svd`, `propagator` will work, as will `method="direct", solver="lstsq"`.

Since the solution is not unique, any valid steady state can be returned.

The method `propagator` can take an initial `rho` to control the resulting steady state:
```
A = rand_dm(2)
B = rand_dm(2)
assert steadystate(H, c, method="propagator", rho=(A & B)) == A & fock_dm(2, 0)
```


The default method for steadystate may have changed since the `piqs` example was created and it need to be updated.

**Comment by Ericgig** [comment]
In your first example, looking at the Eigen values, it's degenerate:
```
from qutip import piqs
N = 10
system = piqs.Dicke(N, emission = 1, pumping = 2)
L = system.liouvillian()
L.eigenenergies(eigvals=10, sort='high')
```
```
array([8.52747114e-10-1.09084443e-23j, 0.00000000e+00+0.00000000e+00j,
       0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
       0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
       0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
       0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j])
```

The piqs module's Liouvillian is not in the same basis as your tries.
With `N=2`, you have 2 spin half mixed in a triplet `m=1, j={-1, 0, 1}` and a singlet `m=0, j=0`.

I would suggest to look at the documentation and tutorials:
https://qutip.readthedocs.io/en/qutip-5.1.x/guide/guide-piqs.html
https://qutip.readthedocs.io/en/qutip-5.1.x/apidoc/piqs.html
https://qutip.org/qutip-tutorials/

ps. `&` has lower operator priority to `+`, so you probably want `(sigmam() & qeye(2)) + (qeye(2) & sigmam())`

**Comment by ChaoXianGaoGuan** [comment]
@Ericgig Thank you for your help! I realized that the `piqs` uses the `Dicke` basis, and now I can construct Hamiltonian correctly and get the right results!
