### ISSUE TITLE
KeyError in _blas_info method

### ISSUE THREAD

**Issue by glassnotes** [qutip/qutip#552]
Hi devs,

I've been running into an issue installing the most recent dev version. The _blas_info() method is throwing the following error:

```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import qutip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/oliviadimatteo/tomo_test/qutip/qutip/__init__.py", line 174, in <module>
    import qutip._mkl
  File "/Users/oliviadimatteo/tomo_test/qutip/qutip/_mkl/__init__.py", line 3, in <module>
    _set_mkl()
  File "/Users/oliviadimatteo/tomo_test/qutip/qutip/_mkl/utilities.py", line 47, in _set_mkl
    if _blas_info() == 'INTEL MKL':
  File "/Users/oliviadimatteo/tomo_test/qutip/qutip/utilities.py", line 405, in _blas_info
    if hasattr(config,'mkl_info') or any('mkl' in lib for lib in blas_info['libraries']):
KeyError: 'libraries'
```

It seems this method was changed most recently in commit d7bb119 to include a line containing `blas_info['libraries']`. For reference I am doing a basic installation with just numpy (1.11.2), scipy (0.18.1), and cython (0.24.1), and not with any of the fortran MC stuff. I'm using Mac OSX 10.11, and Python 3.5.2. [I've also been able to successfully install using a commit from before this, a31f7fc.] 

Please let me know if there is just something I've missed here. Thanks!

**Comment by nonhermitian** [comment]
if you run:

```python
import numpy as np
config = np.__config__
config.show()
```
what do you get?

**Comment by glassnotes** [comment]
Hi, 

Here's the output I get. While I've installed the BLAS libraries on my machine, I haven't 'connected' it with numpy, so maybe this is what's leading to the issue?

```
>>> import numpy as np
>>> config = np.__config__
>>> config.show()
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
blas_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
lapack_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
    extra_compile_args = ['-msse3']
atlas_3_10_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
```

**Comment by nonhermitian** [comment]
Well it seems that you are using the OSX accelerate BLAS. It is just missing the libraries key in the dict. Simple fix, will do today.  Thanks for finding this.

**Comment by nonhermitian** [comment]
Should be fixed now.  Let me know if latest dev version works.

**Comment by nonhermitian** [comment]
I am guessing that this is closed.

**Comment by glassnotes** [comment]
Apologies, I encountered a separate set of issues related to cython that I have thus far been unable to solve. Once I get that sorted out, if I run into any errors related to the above, I'll get back to you. Thanks!

**Comment by nonhermitian** [comment]
In our Cython code, or your own?

**Comment by glassnotes** [comment]
I don't think it's your code, but I haven't looked in to it in sufficient detail yet. As it stands installing qutip is fine but importing it fails, as it is unable to find the C headers, and is spitting out multiple errors of the form "distutils.errors.CompileError: command '/usr/bin/clang' failed with exit status 1". I can provide the full error messages sometime tomorrow if I'm still unable to solve the problem.

**Comment by glassnotes** [comment]
Okay I figured out what was going wrong, and it was my bad. Thanks a bunch!
