### ISSUE TITLE
Kraus operator function leads to segmentation fault on MacOS

### ISSUE THREAD

**Issue by quantshah** [qutip/qutip#944]
I was trying to figure out why tests on #943 and #942 were failing for MacOS and could pin-point it down to the `qutip.superop_reps.to_kraus` function. The test `tests.test_superop_reps.test_ChoiKrausChoi` leads to the same malloc error with the message,
```
python(2234,0x7fff95aef380) malloc: *** error for object 0x7fde6f2f0ff0: incorrect checksum for freed object - object was probably modified after being freed.
```
Investigating more.

**Comment by nonhermitian** [comment]
I have seen this quite a bit in the tests. Calling the code outside of the test always works. So it could be the test suite, which is based on the out of date nose, needs to be updated.

**Comment by sahmed95** [comment]
So, do you suggest changing to something like [pyTest](https://github.com/pytest-dev/pytest/) or just switching off the troublesome tests for now and discussing the issue for a long term change. All new PRs might face this issue and we won't be able to merge new code till this is resolved. Thanks for taking a look.

**Comment by nonhermitian** [comment]
I would verify that the code in question does indeed work when run outside the test franework. If so, then it is likely that the tests need to be moved to pytest.

**Comment by ajgpitch** [comment]
@sahmed95 I assume that you still have a Mac for testing this locally?

**Comment by sahmed95** [comment]
Yes. The tests run fine on a Mac if I call it with just python. But they fail if I run the test suite with nosetests.

**Comment by ajgpitch** [comment]
I have had a bit of a read around 'incorrect checksum for freed object'. I don't think there's anything wrong with our stuff. This must be an issue with Python on MacOS. I suggest just merge the PRs and hopefully someone will fix the underlying issue at some point

**Comment by ajgpitch** [comment]
@quantshah why did we close this? The tests are still failing. Did you close it because it only happens with the tests? If so, then maybe we should open another issue specifically about that.
I would be happy just to leave this open until the MacOS test are working again.
